In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection  import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

## PreProcessing

In [4]:
data =  data.drop(['RowNumber', 'CustomerId', 'Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# encode
lebel_encoder = LabelEncoder()
data['Gender'] = lebel_encoder.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
data['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [8]:
ohe = OneHotEncoder()

geo_encoded = ohe.fit_transform(data[['Geography']])

geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=ohe.get_feature_names_out(['Geography'])
)

geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# combaine the datasets
data= pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
## Save the encoder and scaler 
with open('lebel_encoder_gender.pkl','wb') as file:
    pickle.dump(lebel_encoder,file)
with open('oneHotEncoder_geo.pkl','wb') as file:
    pickle.dump(ohe,file)

# Split The DataSet

In [11]:
X = data.drop('Exited',axis=1)
y = data['Exited']


# train test split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [12]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
8371,813,0,29,5,106059.40,1,0,0,187976.88,0.0,1.0,0.0
5027,681,1,37,8,73179.34,2,1,1,25292.53,0.0,1.0,0.0
9234,642,1,49,4,120688.61,1,1,0,24770.22,0.0,1.0,0.0
3944,612,0,31,8,117989.76,1,1,1,54129.86,1.0,0.0,0.0
6862,586,1,33,9,0.00,1,1,0,6975.02,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,768,1,54,8,69712.74,1,1,1,69381.05,1.0,0.0,0.0
5191,682,0,58,1,0.00,1,1,1,706.50,1.0,0.0,0.0
5390,735,0,38,1,0.00,3,0,0,92220.12,1.0,0.0,0.0
860,667,1,43,8,190227.46,1,1,0,97508.04,1.0,0.0,0.0
7270,697,1,51,1,147910.30,1,1,1,53581.14,0.0,1.0,0.0

In [14]:
y_train

8371    1
5027    0
9234    1
3944    0
6862    0
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 6700, dtype: int64

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [16]:
X_train

array([[ 1.67588802, -1.10022343, -0.94183739, ..., -1.00388816,
         1.74875572, -0.57987798],
       [ 0.30320673,  0.9089063 , -0.17987213, ..., -1.00388816,
         1.74875572, -0.57987798],
       [-0.10235819,  0.9089063 ,  0.96307575, ..., -1.00388816,
         1.74875572, -0.57987798],
       ...,
       [ 0.86475817, -1.10022343, -0.08462648, ...,  0.9961269 ,
        -0.57183516, -0.57987798],
       [ 0.15761932,  0.9089063 ,  0.39160181, ...,  0.9961269 ,
        -0.57183516, -0.57987798],
       [ 0.46959234,  0.9089063 ,  1.15356706, ..., -1.00388816,
         1.74875572, -0.57987798]], shape=(6700, 12))

In [17]:
X_test

array([[-0.53150066,  0.91958555, -0.66802418, ..., -1.00060624,
         1.68705478, -0.56148468],
       [-0.25478739,  0.91958555,  0.38332105, ...,  0.99939412,
        -0.59274898, -0.56148468],
       [-0.48025747, -1.0874464 ,  0.47889789, ..., -1.00060624,
        -0.59274898,  1.78099249],
       ...,
       [-0.60324114, -1.0874464 , -0.76360102, ...,  0.99939412,
        -0.59274898, -0.56148468],
       [-2.15078573,  0.91958555,  2.00812732, ...,  0.99939412,
        -0.59274898, -0.56148468],
       [ 0.58560106, -1.0874464 ,  0.67005157, ..., -1.00060624,
         1.68705478, -0.56148468]], shape=(3300, 12))

In [18]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)